Claranet/Models/ClienteModel.cs
using System.ComponentModel.DataAnnotations;

namespace Claranet.Models
{
    public class ClienteModel
    {
        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Cnpj")]
        public string cnpj { get; set; }

        [Display(Name = "Razao social")]
        public string razaoSocial { get; set; }

        [Display(Name = "Nome fantasia")]
        public string nomeFantasia { get; set; }

        [Display(Name = "Email")]
        public string email { get; set; }

        [Display(Name = "Telefone")]
        public string telefone { get; set; }

        [Display(Name = "Telefone Comercial")]
        public string telComercial { get; set; }
        
        [Display(Name = "Celular")]
        public string celular { get; set; }

        [Display(Name = "Logradouro")]
        public string logradouro { get; set; }

        [Display(Name = "numero")]
        public string numero { get; set; }

        [Display(Name = "Complemento")]
        public string complemento { get; set; }

        [Display(Name = "Bairro")]
        public string bairro { get; set; }

        [Display(Name = "Cidade")]
        public string cidade { get; set; }

        [Display(Name = "Estado")]
        public string estado { get; set; }

        [Display(Name = "Cep")]
        public string cep { get; set; }

        [Display(Name = "Nome Contato")]
        public string nomeContato { get; set; }

        [Display(Name = "Senha")]
        public string senha { get; set; }
    }
}

Claranet/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;

namespace Claranet.Models
{
    public class Contexto : DbContext
    {
        public DbSet<ClienteModel> Clientes { get; set; }

        public Contexto(DbContextOptions<Contexto> db) : base(db)
        {

        }
    }
}

Claranet/Controllers/CadastroController.cs
using Claranet.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Claranet.Controllers
{
    public class CadastroController : Controller
    {
        private readonly Contexto _Contexto;

        public CadastroController(Contexto contexto)
        {
            _Contexto = contexto;
        }
        public IActionResult cadastroCliente()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> consultaCliente(int id)
        {
          ClienteModel cliente = await _Contexto.Clientes.FindAsync(id);
            return View(cliente);   
        }

        [HttpPost]
        public async Task<IActionResult> AddCliente(ClienteModel cliente)
        {
            await _Contexto.Clientes.AddAsync(cliente);
            await _Contexto.SaveChangesAsync();
            return RedirectToAction("index", "home");

        } 
    }
}

Claranet/Controllers/HomeController.cs
using Claranet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Claranet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult index()
        {
            return View();
        }  
    }
}

Claranet/Views/Cadastro/cadastroCliente.cshtml
@model IEnumerable<ClienteModel>

@{
    ViewData["Title"] = "cadastroCliente";
}
<div class="container">
    <div class="text-center">
        <h1 class="h3 mb-3 font-weight-normal">Tela de cadastro</h1>
    </div>
    <form asp-controller="Cadastro" asp-action="AddCliente" method="post">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="nomeContato">Nome contato</label>
                    <input type="text" class="form-control" name="nomeContato" id="nomeContato" placeholder="Nome de contato" >
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="cnpj">CNPJ/Login</label>
                    <input type="text" class="form-control" id="cnpj" name="cnpj" onkeypress="return event.charCode >= 48 && event.charCode <= 57"  placeholder="Digite o cnpj" required>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="enderecoEmail">Endereço de email</label>
                    <input type="email" class="form-control" name="email" id="enderecoEmail" placeholder="nome@exemplo.com" required>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="nomeFantasia">Nome Fantasia</label>
                    <input type="text" class="form-control" name="nomeFantasia" id="nomeFantasia" placeholder="Digite seu nome fantasia">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="exampleFormControlInput1">Telefone</label>
                    <input type="text" class="form-control" name="telefone" id="telefone" onkeypress="return event.charCode >= 48 && event.charCode <= 57" placeholder="Digite seu telefone">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="telComercial">Telefone comercial</label>
                    <input type="text" class="form-control" name="telComercial" id="telComercial" onkeypress="return event.charCode >= 48 && event.charCode <= 57" placeholder="Digite seu telefone comercial">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="celular">Celular</label>
                    <input type="text" class="form-control" name="celular" id="celular" onkeypress="return event.charCode >= 48 && event.charCode <= 57" placeholder="Digite seu celular">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="logradouro">Logradouro</label>
                    <input type="text" class="form-control" name="logradouro" id="logradouro" placeholder="Seu logradouro">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="numero">Numero</label>
                    <input type="text" class="form-control" name="numero" id="numero" onkeypress="return event.charCode >= 48 && event.charCode <= 57" maxlength="4" placeholder="Seu numero">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="complemento">Complemento</label>
                    <input type="text" class="form-control" name="complemento" id="complemento" placeholder="Seu complemento">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="bairro">Bairro</label>
                    <input type="text" class="form-control" name="bairro" id="bairro" placeholder="Seu bairro">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="cidade">Cidade</label>
                    <input type="text" class="form-control" name="cidade" id="cidade" placeholder="Sua cidade">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="estado">Estado</label>
                    <input type="text" class="form-control" name="estado" id="estado" placeholder="Seu estado">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" name="cep" id="cep" onkeypress="return event.charCode >= 48 && event.charCode <= 57" placeholder="Seu Cep">
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input type="password"  id="senha" class="form-control" name="senha" placeholder="Sua senha" maxlength="20" required>
                </div>
            </div>
        </div>
        <div class="text-right">
            <button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("index", "Home")'">Voltar</button>
            <input type="submit" id="cadastrar" value="cadastrar" onclick="btnCadastrar()" class="btn btn-success">
        </div>
    </form>
</div>
@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <script src="~/js/CadastroCliente/CadastroCliente.js"></script>
    <script>
        function btnCadastrar() {
            let cnpj = $('#cnpj').val();
            let email = $('#enderecoEmail').val();
            let senha = $('#senha').val();
            let nomeContato = $('#nomeContato').val();
            console.log(cnpj, email, senha);
            if (cnpj != '' || email != '' || senha != '' || nomeContato != '') {
                location.href = '@Url.Action("AddCliente", "Cadastro")';
            }
            else {
                alert("Campo CNPJ, EMAIL e SENHA devem estar preenchidos.");
            }
        }
    </script>
}

Claranet/Views/Cadastro/consultaCliente.cshtml
@model IEnumerable<Claranet.Models.ClienteModel>

@{
    ViewData["Title"] = "consultaCliente";
}

<h1>consultaCliente</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cnpj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.razaoSocial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nomeFantasia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telComercial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.celular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.logradouro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.complemento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bairro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nomeContato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.senha)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cnpj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.razaoSocial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomeFantasia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telComercial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.celular)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.logradouro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.complemento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bairro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomeContato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.senha)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Claranet/Views/Home/index.cshtml
@model Claranet.Models.ClienteModel
@{

    ViewData["Title"] = "Home Page";
}
<html>
<head>
</head>
<body class="text-center">
    <div class="container-fluid">
        <form class="form-group">
            <h1 class="h3 mb-3 font-weight-normal">Faça login</h1>
            <div class="row justify-content-center">
                <div class="col-6 text-center">
                    <label for="labelLogin" class="sr-only">Login</label>
                    <input type="text" id="inputEmail" class="form-control" placeholder="Seu cnpj" required="" autofocus="">
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-6 text-center">
                    <label for="inputPassword" class="sr-only">Senha</label>
                    <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required="">
                </div>
            </div>
        </form>
        <div class="row justify-content-md-center">
            <div class="col-6">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Entrar</button>
            </div>
        </div>
         <div class="row justify-content-md-center">
            <div class="col-4">
                <a asp-action="EsqueceuSenha">Esqueceu a senha?</a>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-4 text-center">
                <a>Novo por aqui?</a>
                <a asp-controller="Cadastro" asp-action="cadastroCliente">Criar cadastro</a>
            </div>
        </div>
    </div>
</body>
</html>

Claranet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Claranet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CLARANET</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="index">Login</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Felipe Pereira - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>